### PR TITLE
Make statemachine_name optional in PlantUML files

### LINKED ISSUE #438: Make statemachine name optional in PlantUML files
Currently, statesmith silently skips over any plant uml file with a `@startuml` directive that is missing a statemachine name, eg `@startuml statemachine_name`.

This is unexpected behavior for a couple of reasons.
1. The file is silently skipped, leading to user confusion (especially for new users)
2. The vast majority of plantuml examples on the web do not have anything after `@startuml`. A new user could reasonably expect to process a simple plantuml example with statesmith as-is, but it will almost certainly fail.

### PR DESCRIPTION
**Pull request by emmby**
This PR makes statemachine name optional in plantuml files. If the name is missing in the file, it will infer the name from the filename.

Separately, it also simplifies the compilation of antlr g4 scripts, reducing the number of scripts as well as making them work in other shells besides bash.

Fixes #438

### CODE REVIEW

File: src/StateSmith/Input/PlantUML/PlantUMLWalker.cs [hunk 1]
```diff
@@ -125,9 +127,8 @@ public override void EnterDiagram([NotNull] PlantUMLParser.DiagramContext contex
     {
         root.id = context.startuml().statemachine_name()?.GetText() ?? "";
 
-        if (root.id == "")
-        {
-            ThrowValidationFailure("PlantUML diagrams need a name and should start like `@startuml MySmName`", context.startuml());
+        if( root.id == "") {
+            root.id = Path.GetFileNameWithoutExtension(filepath);
```
Comment (adamfk) [inline src/StateSmith/Input/PlantUML/PlantUMLWalker.cs:131]: We also need to handle invalid characters for a state machine class name.

For example, consider if the input file is `22nd-design.puml`? We can't code generate a class called `22nd-design`.

One quick idea:
1. strip all characters that don't match `[0-9a-zA-Z_]`
2. then if the first character doesn't match `[a-zA-Z_]`, we prepend `sm_`?

**Review by adamfk — CHANGES_REQUESTED** [review]
This looks really good! And you are correct. I think this will be quite helpful for users.

**Comment by adamfk** [comment]
Can you also please add a quick note in the release notes?

File: src/StateSmith/Input/PlantUML/PlantUMLWalker.cs (hunk 1 above)
Comment (emmby) [reply src/StateSmith/Input/PlantUML/PlantUMLWalker.cs]: Good point, I added a method to sanitize the filename based on your suggestion and added some tests.

**Review by adamfk — APPROVED** [review]
Awesome possum! Thanks again!
